group: edge
dist: trusty

language: java
jdk:
  - openjdk8
  - oraclejdk8

install: true
before_install:
  - sudo apt update

  # install docker-compose
  - sudo apt install -y python-pip curl jq libxml2-utils
  - sudo pip install docker-compose httpie
  - sudo usermod -aG docker $(whoami)

  # kill whatever punning on postgres / rabbitmq port
  - sudo kill $(sudo lsof -t -i:5432) | true
  - sudo kill $(sudo lsof -t -i:5672) | true
  - sudo kill $(sudo lsof -t -i:27017) | true

script:
  - bash gradlew clean test jgiven build

  - export APP_UPLOAD_PATH="$PWD/file-storage"
  - mkdir -p $APP_UPLOAD_PATH
  - cp -Rf build/libs "$APP_UPLOAD_PATH/"

  # docker
  - bash gradlew appUp
  - http --auth user:password :8001/health
  - http --auth user:password -f post :8002/upload filename="build.gradle" file@build.gradle
  - http --auth user:password -f post :8002/upload filename="settings.gradle" file@settings.gradle
  - http --auth user:password :8002/api/v1/files
  - http --auth user:password :8002/
  - bash gradlew appDown

  # h2
  - bash gradlew clean assemble
  - bash ./build/libs/*jar --app.upload.path=$APP_UPLOAD_PATH --spring.profiles.active=db-h2 &
  - sleep 25
  - http --auth user:password :8001/health
  - http --auth user:password -f post :8002/upload filename="build.gradle" file@build.gradle
  - http --auth user:password -f post :8002/upload filename="settings.gradle" file@settings.gradle
  - http --auth user:password :8002/api/v1/files
  - http --auth user:password :8002/
  - >
    export APPLICATION_PID=$(ps waux|grep streaming-file-server|grep -v 'grep'|awk '{print $2}');
    for P_ID in "$APPLICATION_PID"; do
      if [ "''" != "'$P_ID'" ]; then
        echo "killing $P_ID";
        kill "-9" ${P_ID}
      fi
    done

  # install as linux service
  - bash gradlew clean assemble dockerUp
  - cp -Rf build/libs "$APP_UPLOAD_PATH/"
  - mv -f ./build/libs/*.jar /tmp/streaming-file-server.jar
  - sudo ln -s /tmp/streaming-file-server.jar /etc/init.d/streaming-file-server
  - sudo service streaming-file-server start
  - sleep 30
  - http --auth user:password :8001/health
  - http --auth user:password :8002/health
  - http --auth user:password -f post :8002/upload filename="readme" file@README.md
  - http --auth user:password :8002/api/v1/files
  - http --auth user:password :8002/
  - sudo service streaming-file-server stop
  - bash gradlew dockerDown

after_script:
  - bash gradlew dependencyUpdates -Drevision=release
  - bash gradlew --stop

cache:
  directories:
    - $HOME/.gradle/
    - .gradle/
