group: edge
dist: trusty

language: java
jdk:
  - openjdk8
  - oraclejdk8

install: true
before_install:
  - sudo apt update

  # install docker-compose
  - sudo apt install -y python-pip curl jq libxml2-utils
  - sudo pip install docker-compose httpie
  - sudo usermod -aG docker $(whoami)

  # kill whatever punning on postgres / rabbitmq port
  - sudo kill $(sudo lsof -t -i:5432) | true
  - sudo kill $(sudo lsof -t -i:5672) | true
  - sudo kill $(sudo lsof -t -i:27017) | true

#  # gradle
#  - curl -s "https://get.sdkman.io" | bash
#  - mkdir -p "$HOME/.sdkman/etc"
#  - touch "$HOME/.sdkman/etc/config"
#  - sed -i -e 's/^sdkman_auto_answer=false$/sdkman_auto_answer=true/g' "$HOME/.sdkman/etc/config"
#  - source "$HOME/.sdkman/bin/sdkman-init.sh"
#  - sdk use gradle
#  - source "$HOME/.sdkman/bin/sdkman-init.sh"

script:
  - bash gradlew clean build jgiven

  - cp -Rf build files/
  - export APP_PATH="$PWD/files"
  - bash gradlew appUp
  - http -f post :8080/upload filename="build.gradle" file@build.gradle
  - http -f post :8080/upload filename="settings.gradle" file@settings.gradle
  - http :8080/api/v1/files
  - http :8080/
  - bash gradlew appDown

  - bash gradlew dockerUp
  - sudo mkdir -p /var/app
  - sudo mv -f build/libs/*.jar /var/app/fileserver.jar
  - sudo ln -s /var/app/fileserver.jar /etc/init.d/fileserver
  - sudo service fileserver start
  - sleep 15
  - http -f post :8080/upload filename="readme" file@README.md
  - http :8080/
  - http :8080/api/v1/files
  - bash gradlew dependencyUpdates -Drevision=release

after_script:
  - sudo service fileserver stop
  - bash gradlew dockerDown
  - bash gradlew --stop

cache:
  directories:
    - $HOME/.gradle/
    - .gradle/
