group: edge
dist: trusty

language: java
jdk:
  - openjdk8
  - oraclejdk8

install: true
before_install:
  - sudo apt update

  # install docker-compose
  - sudo apt install -y python-pip curl jq libxml2-utils
  - sudo pip install docker-compose httpie
  - sudo usermod -aG docker $(whoami)

  # kill whatever punning on postgres / rabbitmq port
  - sudo kill $(sudo lsof -t -i:5432) | true
  - sudo kill $(sudo lsof -t -i:5672) | true
  - sudo kill $(sudo lsof -t -i:27017) | true

script:
  - bash gradlew clean test jgiven build

  - export APP_UPLOAD_PATH="$PWD/file-storage"
  - mkdir -p $APP_UPLOAD_PATH
  - cp -Rf build "$APP_UPLOAD_PATH/"

  - bash gradlew appUp
  - http -f post :8080/upload filename="build.gradle" file@build.gradle
  - http -f post :8080/upload filename="settings.gradle" file@settings.gradle
  - http :8080/api/v1/files
  - http :8080/
  - bash gradlew appDown

  - bash gradlew clean assemble
  - bash ./build/libs/*jar --app.upload.path=$APP_UPLOAD_PATH --spring.profiles.active=h2-db &
  - sleep 30
  - http -f post :8080/upload filename="build.gradle" file@build.gradle
  - http -f post :8080/upload filename="settings.gradle" file@settings.gradle
  - http :8080/api/v1/files
  - http :8080/
  - >
    export APPLICATION_PID=$(ps waux|grep streaming-file-server|grep -v 'grep'|awk '{print $2}');
    for P_ID in "$APPLICATION_PID"; do
      if [ "''" != "'$P_ID'" ]; then
        echo "killing $P_ID";
        kill "-9" ${P_ID}
      fi
    done

  - bash gradlew dockerUp
  - sudo mkdir -p /var/app
  - sudo mv -f build/libs/*.jar /var/app/fileserver.jar
  - sudo ln -s /var/app/fileserver.jar /etc/init.d/fileserver
  - sudo service fileserver start
  - sleep 15
  - http -f post :8080/upload filename="readme" file@README.md
  - http :8080/
  - http :8080/api/v1/files
  - sudo service fileserver stop
  - bash gradlew dockerDown

after_script:
  - bash gradlew dependencyUpdates -Drevision=release
  - bash gradlew --stop

cache:
  directories:
    - $HOME/.gradle/
    - .gradle/
