spring:
  active:
    profiles: h2-db
  datasource:
    url: jdbc:h2:mem:${db.name};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${db.user}
    password: ${db.pass}
    database: postgresql
