version: "2.1"

services:

  postgres:
    extends:
      file: ../postgres/docker-compose.yml
      service: postgres
    networks: [backing-services]

  file-items-service:
    build:
      context: ../..
      dockerfile: ./docker-modules/all/file-items-service/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
    image: 127.0.0.1:5000/file-items-service
    ports: ["8001:8001"]
    volumes: ["file-items-service-data:/home/app"]
    networks: [backing-services]

  file-server:
    build:
      context: ../..
      dockerfile: ./docker-modules/all/file-server/Dockerfile
    depends_on:
      file-items-service:
        condition: service_healthy
    environment:
      FILE_ITEMS_REST_SERVICE_HOST: file-items-service
      FILE_ITEMS_REST_SERVICE_PORT: 8001
      #APP_UPLOAD_PATH: /home/app/file-storage
    image: 127.0.0.1:5000/file-server
    ports: ["8002:8002"]
    volumes:
      - ./application-modules/file-server/file-storage:/home/app/file-storage:rw
      - ./application-modules/file-server/build:/home/app/file-storage
      - file-server-data:/home/app
    networks: [backing-services]

volumes:
  postgres-data: {}
  file-items-service-data: {}
  file-server-data: {}

networks:
  backing-services:
    driver: bridge
