version: "2.1"

services:

  postgres:
    image: healthcheck/postgres:alpine
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks: [backing-services]

networks:
  backing-services:
    driver: bridge
