version: "2.1"

services:

  db:
    image: healthcheck/postgres:alpine
    ports: ["5432:5432"]
    volumes: ["db-data:/var/lib/postgresql/data"]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks: [app-backing-services]

  app:
    build:
      context: ../../..
      dockerfile: ./modules/app/src/Dockerfile
    depends_on: [db]
    environment:
      DB_HOST: db
      DB_PORT: 5432
      #APP_UPLOAD_PATH: /tmp/file-storage
    image: 127.0.0.1:5000/app
    ports: ["8080:8080"]
    volumes:
      - ./file-storage:/tmp/file-storage:rw
      - ./build:/tmp/file-storage
      - app-data:/tmp/app
    networks: [app-backing-services]

volumes:
  db-data: {}
  app-data: {}

networks:
  app-backing-services:
    driver: bridge
